name: CI
on:
  pull_request:
    branches: [main]
jobs:
  run_awesome_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: ## fetch depth 0 fetches all git history for repo age
          fetch-depth: 0
      - name: Run awesome-lint
        run: npx awesome-lint
